#!/bin/bash

SLURM_ETC=$1
TRACE_FILE=$2
TRACE_DIR=$(dirname "${TRACE_FILE}")
SLURM_SIMULATOR=/opt/slurm
SLURM_SIMULATOR_ETC=${SLURM_SIMULATOR}/etc

# link generated users.sim in Trace dir to Etc dir, for being used by Slurm Simulator.
# `users.sim` file MUST be Available in TRACE_DIR, file name was fixed by conventions.
ln -s ${TRACE_DIR}/users.sim ${SLURM_SIMULATOR_ETC}/users.sim

# Set trace file to be simulated for this run.
sed 's|###JobsTraceFile###|'$TRACE_FILE'|g' ${SLURM_ETC}/sim.conf.tmpl \
  > ${SLURM_ETC}/sim.conf 

overide_conf --config ${SLURM_ETC}/sim.conf --overide /default/sim.conf > ${SLURM_SIMULATOR_ETC}/sim.conf
overide_conf --config ${SLURM_ETC}/slurm.conf --overide /default/slurm.conf > ${SLURM_SIMULATOR_ETC}/slurm.conf
overide_conf --config ${SLURM_ETC}/slurmdbd.conf --overide /default/slurmdbd.conf > ${SLURM_SIMULATOR_ETC}/slurmdbd.conf
cp ${SLURM_ETC}/topology.conf ${SLURM_SIMULATOR_ETC}/topology.conf
cp ${SLURM_ETC}/slurm.cert ${SLURM_SIMULATOR_ETC}/slurm.cert
cp ${SLURM_ETC}/slurm.key ${SLURM_SIMULATOR_ETC}/slurm.key



# Initialize slurmdb daemon as background for thir run.
# Waiting for mariadb to be up and running. and also for slurmdbd. 
mysqld_safe &
sleep 10
mysql -e "create user 'slurm'@'localhost' identified by 'slurm';"
mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'slurm'@'localhost' IDENTIFIED BY 'slurm';"
slurmdbd -Dvvv &
sleep 10

# Initialize Account script
# `init_account` file MUST be Available in TRACE_DIR, file name was fixed by conventions.
${TRACE_DIR}/init_account

# Start Running Simulation by running SlurmCtld as daemon on foreground.
slurmctld -Dvvv

mv /var/log/slurm/* .

cluster="$(get_slurm_conf --config ${SLURM_SIMULATOR_ETC}/slurm.conf --parameter ClusterName )"

process_sdiag --sdiag sdiag.out
process_simstat --simstat simstat.out
process_sinfo --sinfo sinfo.out --cluster $cluster
process_sprio --sprio sprio.out
process_squeue --squeue squeue.out --cluster $cluster